Database:
  DSN: >- 
    user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
  DefaultStringSize: 255
  MaxOpenConns: 100
  MaxIdleConns: 100
  ConnMaxIdleTime: 3600s

# 用于加密盐值的AESKey
AESKeyForUserLoginPWSalt: >-
  abcdefgehjhijkmlkjjwwoew

Debug: true

# for web app use
WebSettings:
  Port: 8080

  LimitSetting:
    Burst: 10
    Limit: 10